name: minichatapp.net

services:
    app:
        build:
            context: .
            dockerfile: MiniChatApp.Server/Dockerfile
        image: minichatapp/v3
        container_name: minichatapp-container
        ports: 
            - 3008:3008
        working_dir: /app
        networks:
            - minichatapp-network
        environment:
            ConnectionStrings__MiniChatApp: mongodb://db:27017
            DatabaseName : MiniChatApp
    db:
        image: mongo
        container_name: minichatapp-db
        ports:
            - 2004:27017
        networks:
            - minichatapp-network
networks:
    minichatapp-network:
        